/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/68275e863c5ab94b9eacc586.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useScroll } from "@react-three/drei";
import { useGLTF } from "../lib/useGLTF";
import { useFrame } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";

import * as THREE from "three";
import { ANIMATION_CONSTANTS } from "../constants/animation";
import { useMobile } from "../contexts/MobileContext";

export function Avatar(props) {
  const { nodes, materials } = useGLTF("/models/68275e863c5ab94b9eacc586.glb");
  const { animations: idleAnimation } = useGLTF("/animations/Happy-Idle.glb");
  const { animations: walkingAnimation } = useGLTF("/animations/Walking.glb");

  // Clone animations and strip tracks targeting "Armature" — the Mixamo skeleton
  // root node that doesn't exist in the avatar model (whose root is "Hips")
  const animations = useMemo(() => {
    const cloneAndFilter = (clip, name) => {
      const cloned = clip.clone();
      cloned.name = name;
      cloned.tracks = cloned.tracks.filter(
        (track) => !track.name.startsWith("Armature."),
      );
      return cloned;
    };
    return [
      cloneAndFilter(idleAnimation[0], "Idle"),
      cloneAndFilter(walkingAnimation[0], "Walking"),
    ];
  }, [idleAnimation, walkingAnimation]);

  const group = useRef();
  const { actions } = useAnimations(animations, group);
  // Blend weight of the walk (idle is 1 - this).
  const walkWeight = useRef(0);

  // Both clips play for the whole session; the walk/idle blend is a single
  // weight driven per frame. Neither action is reset or stopped while mounted,
  // so the walk resumes from wherever its cycle is, and a cross-fade always continues
  // from the current weight (retargeting mid-fade never jumps).
  useEffect(() => {
    const idle = actions.Idle;
    const walking = actions.Walking;
    if (!idle || !walking) return;
    idle.setEffectiveWeight(1 - walkWeight.current);
    walking.setEffectiveWeight(walkWeight.current);
    idle.play();
    walking.play();
    return () => {
      idle.stop();
      walking.stop();
    };
  }, [actions]);

  const scrollData = useScroll();
  const lastScroll = useRef(0);
  // Time left, in seconds, before the walk state ends after the last movement.
  const walkHold = useRef(0);
  const { isMobile, prefersReducedMotion } = useMobile();

  // Safe: R3F useFrame re-captures the closure on each render
  useFrame((_, delta) => {
    const scrollDelta = scrollData.offset - lastScroll.current;
    let rotationTarget = 0;

    if (Math.abs(scrollDelta) > ANIMATION_CONSTANTS.SCROLL_DELTA_THRESHOLD) {
      walkHold.current = ANIMATION_CONSTANTS.WALK_HOLD_MS / 1000;
      if (scrollDelta > 0) {
        rotationTarget = isMobile
          ? ANIMATION_CONSTANTS.MOBILE_FORWARD_ROTATION
          : 0;
      } else {
        rotationTarget = isMobile
          ? ANIMATION_CONSTANTS.MOBILE_BACKWARD_ROTATION
          : ANIMATION_CONSTANTS.DESKTOP_BACKWARD_ROTATION;
      }
    } else {
      walkHold.current = Math.max(0, walkHold.current - delta);
    }

    // Skip walk/idle transitions when user prefers reduced motion
    const walking = walkHold.current > 0 && !prefersReducedMotion;
    const target = walking ? 1 : 0;
    const current = walkWeight.current;
    if (current !== target) {
      const duration = walking
        ? ANIMATION_CONSTANTS.ANIMATION_FADE_IN_DURATION
        : ANIMATION_CONSTANTS.ANIMATION_FADE_OUT_DURATION;
      const step = delta / duration;
      const next = target > current
        ? Math.min(target, current + step)
        : Math.max(target, current - step);
      walkWeight.current = next;
      // Weights sum to 1, so the mixer blends the two poses without leaking
      // the bind pose in.
      actions.Walking?.setEffectiveWeight(next);
      actions.Idle?.setEffectiveWeight(1 - next);
    }

    // damp() is frame-rate independent (unlike fixed-alpha lerp per frame)
    group.current.rotation.y = THREE.MathUtils.damp(
      group.current.rotation.y,
      rotationTarget,
      ANIMATION_CONSTANTS.ROTATION_DAMP_LAMBDA,
      delta,
    );
    lastScroll.current = scrollData.offset;
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Glasses"
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Headwear"
        geometry={nodes.Wolf3D_Headwear.geometry}
        material={materials.Wolf3D_Headwear}
        skeleton={nodes.Wolf3D_Headwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/68275e863c5ab94b9eacc586.glb");
useGLTF.preload("/animations/Happy-Idle.glb");
useGLTF.preload("/animations/Walking.glb");
