/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/68275e863c5ab94b9eacc586.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useFBX, useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useMemo, useRef, useState } from "react";

import * as THREE from "three";
import { ANIMATION_CONSTANTS } from "../constants/animation";
import { useMobile } from "../contexts/MobileContext";

export function Avatar(props) {
  const { nodes, materials } = useGLTF("/models/68275e863c5ab94b9eacc586.glb");
  const { animations: idleAnimation } = useFBX("/animations/Happy-Idle.fbx");
  const { animations: walkingAnimation } = useFBX("/animations/Walking.fbx");

  // Clone animations and strip tracks targeting "Armature" — the FBX skeleton
  // root node that doesn't exist in the GLB avatar model (whose root is "Hips")
  const animations = useMemo(() => {
    const cloneAndFilter = (clip, name) => {
      const cloned = clip.clone();
      cloned.name = name;
      cloned.tracks = cloned.tracks.filter(
        (track) => !track.name.startsWith("Armature."),
      );
      return cloned;
    };
    return [
      cloneAndFilter(idleAnimation[0], "Idle"),
      cloneAndFilter(walkingAnimation[0], "Walking"),
    ];
  }, [idleAnimation, walkingAnimation]);

  const group = useRef();
  const { actions } = useAnimations(animations, group);

  const [animation, setAnimation] = useState("Idle");
  const animationRef = useRef(animation);
  useEffect(() => {
    if (actions[animation]) {
      actions[animation]
        .reset()
        .fadeIn(ANIMATION_CONSTANTS.ANIMATION_FADE_IN_DURATION)
        .play();
      return () => {
        if (actions[animation]) {
          actions[animation].fadeOut(
            ANIMATION_CONSTANTS.ANIMATION_FADE_OUT_DURATION,
          );
        }
      };
    }
  }, [animation, actions]);

  const scrollData = useScroll();
  const lastScroll = useRef(0);
  const { isMobile, prefersReducedMotion } = useMobile();

  // Safe: R3F v8 useFrame re-captures the closure on each render
  useFrame(() => {
    const scrollDelta = scrollData.offset - lastScroll.current;
    let rotationTarget = 0;
    let targetAnimation = "Idle";

    if (Math.abs(scrollDelta) > ANIMATION_CONSTANTS.SCROLL_DELTA_THRESHOLD) {
      targetAnimation = "Walking";
      if (scrollDelta > 0) {
        rotationTarget = isMobile
          ? ANIMATION_CONSTANTS.MOBILE_FORWARD_ROTATION
          : 0;
      } else {
        rotationTarget = isMobile
          ? ANIMATION_CONSTANTS.MOBILE_BACKWARD_ROTATION
          : ANIMATION_CONSTANTS.DESKTOP_BACKWARD_ROTATION;
      }
    }

    // Skip walk/idle transitions when user prefers reduced motion
    if (prefersReducedMotion) {
      targetAnimation = "Idle";
    }

    if (animationRef.current !== targetAnimation) {
      animationRef.current = targetAnimation;
      setAnimation(targetAnimation);
    }

    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      rotationTarget,
      ANIMATION_CONSTANTS.ROTATION_LERP_SPEED,
    );
    lastScroll.current = scrollData.offset;
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Glasses"
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Headwear"
        geometry={nodes.Wolf3D_Headwear.geometry}
        material={materials.Wolf3D_Headwear}
        skeleton={nodes.Wolf3D_Headwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/68275e863c5ab94b9eacc586.glb");
useFBX.preload("/animations/Happy-Idle.fbx");
useFBX.preload("/animations/Walking.fbx");
