/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Balloon.glb -o src/components/Balloon.jsx -r public
Balloon by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/d1gDDhM7pTf)
*/

import { useGLTF } from "@react-three/drei";

export function Balloon(props) {
  const { nodes } = useGLTF("/models/Balloon.glb", "/draco/");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Balloon007.geometry}>
        {/* Own material (roughness/metalness from the GLB's phong1SG) — each
            balloon gets its own color without copying the shared instance */}
        <meshStandardMaterial color={props.color} roughness={0.916} metalness={0} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Balloon.glb", "/draco/");
