/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Star.gltf -o src/components/Star.jsx -r public
Star by Kay Lousberg (https://market.pmnd.rs/model/star)
*/

import { useGLTF } from "../lib/useGLTF";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import { useMobile } from "../contexts/MobileContext";
import { useEmissiveGlow } from "../lib/useEmissiveGlow";

export function Star(props) {
  const { nodes, materials } = useGLTF("/models/Star.glb");
  const { prefersReducedMotion } = useMobile();
  // The star is one of the two models brightened with emissive on desktop.
  useEmissiveGlow(materials["Yellow.030"], 1.8);
  const ref = useRef();
  useFrame((_, delta) => {
    if (!prefersReducedMotion) {
      ref.current.rotation.y += delta * 1.8;
    }
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.star.geometry}
        material={materials["Yellow.030"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/Star.glb");
